### ISSUE TITLE
upload

### ISSUE THREAD

**Issue by Hicck** [heyui/heyui-admin-docs#1]
您好，尊敬的heyui开发者，我想请教下关于组件upload的一些问题？怎么修改为自己上传的服务器勒？

**Comment by vvpvvp** [comment]
请参考网站官方提供的示例。
或者加群提问也可以。
https://www.heyui.top/component/data/plugin/upload#%E4%B8%8A%E4%BC%A0%E7%9A%84%E9%80%9A%E7%94%A8%E7%A4%BA%E4%BE%8B
